# Generated by Django 5.1.6 on 2025-05-06 09:49

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_price', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('shipping_price', models.PositiveIntegerField(default=2000)),
                ('sku', models.CharField(blank=True, editable=False, max_length=19, null=True, unique=True)),
                ('mpn', models.CharField(blank=True, editable=False, max_length=12, null=True, unique=True)),
                ('upc', models.CharField(blank=True, editable=False, max_length=12, null=True, unique=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('stock', models.BooleanField(default=False, editable=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_clearance', models.BooleanField(default=False)),
                ('is_deal_of_the_day', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attributes', models.JSONField(default=dict)),
                ('details', django_ckeditor_5.fields.CKEditor5Field(default='Description is missing', verbose_name='Details')),
                ('features', django_ckeditor_5.fields.CKEditor5Field(default='Description is missing', verbose_name='Features')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_set', to='products.product')),
            ],
        ),
    ]
