# Generated by Django 5.1.6 on 2025-04-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='img/Sample.jpg', null=True, upload_to='products/'),
        ),
    ]
