# Generated by Django 5.1.6 on 2025-05-08 12:58

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='details',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='product',
            name='features',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='Features'),
        ),
    ]
