# Generated by Django 5.1.6 on 2025-05-16 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_category'),
        ('products', '0003_alter_product_details_alter_product_features'),
    ]

    operations = [
    ]
