# Generated by Django 5.2.1 on 2025-05-22 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_categorylevel0_remove_category_parent_categorylevel1_and_more'),
        ('products', '0005_alter_product_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.categorylevel4', verbose_name='Финальная категория'),
        ),
    ]
