# Generated by Django 5.1.6 on 2025-04-22 12:35

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_description_product_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='details',
            field=django_ckeditor_5.fields.CKEditor5Field(default='Description is missing', verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='product',
            name='features',
            field=django_ckeditor_5.fields.CKEditor5Field(default='Description is missing', verbose_name='Features'),
        ),
    ]
