# Generated by Django 5.1.6 on 2025-04-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_discount_price_product_mpn_product_sku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mpn',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True),
        ),
    ]
