# Generated by Django 5.1.6 on 2025-04-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_mpn_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mpn',
            field=models.CharField(blank=True, editable=False, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, editable=False, max_length=19, null=True, unique=True),
        ),
    ]
