# Generated by Django 5.1.6 on 2025-04-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_shipping_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shipping_price',
            field=models.PositiveIntegerField(),
        ),
    ]
