# Generated by Django 5.1.6 on 2025-04-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_shipping_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shipping_price',
            field=models.PositiveIntegerField(default=2000),
        ),
    ]
