# Generated by Django 5.1.6 on 2025-04-23 13:07

import apps.orders.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0012_alter_product_discount_price_alter_product_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipping_protection', models.BooleanField(default=False)),
                ('donate_to_goa', models.BooleanField(default=False)),
                ('donate_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('state', models.CharField(choices=[('Batken', 'Batken'), ('Osh', 'Osh'), ('Jalal-Abad', 'Jalal-Abad'), ('Talas', 'Talas'), ('Naryn', 'Naryn'), ('Issyk-Kul', 'Issyk-Kul'), ('Chui', 'Chui')], max_length=50)),
                ('zip_code', models.CharField(max_length=6, validators=[apps.orders.models.validate_zip])),
                ('giftcard_code', models.CharField(blank=True, max_length=50, null=True)),
                ('discount_code', models.CharField(blank=True, max_length=50, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
