# Generated by Django 5.1.6 on 2025-05-06 09:49

import apps.orders.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('Batken', 'Batken'), ('Osh', 'Osh'), ('Jalal-Abad', 'Jalal-Abad'), ('Talas', 'Talas'), ('Naryn', 'Naryn'), ('Issyk-Kul', 'Issyk-Kul'), ('Chui', 'Chui')], max_length=50)),
                ('zip_code', models.CharField(max_length=6, validators=[apps.orders.models.validate_zip])),
                ('giftcard_code', models.CharField(blank=True, max_length=50, null=True)),
                ('discount_code', models.CharField(blank=True, max_length=50, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('donation', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)])),
                ('subtotal', models.PositiveIntegerField(default=0)),
                ('shipping_fee', models.PositiveIntegerField(default=0)),
                ('protection_fee', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='carts.cart')),
            ],
        ),
    ]
