# Generated by Django 5.1.6 on 2025-04-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='donate_to_goa',
            field=models.IntegerField(default=0, max_length=6),
        ),
    ]
