# Generated by Django 5.1.6 on 2025-04-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_donate_to_goa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='donate_to_goa',
            field=models.IntegerField(default=0),
        ),
    ]
