# Generated by Django 5.1.6 on 2025-04-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_donate_to_goa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='donate_to_goa',
            field=models.IntegerField(blank=True, default=0, max_length=6, null=True),
        ),
    ]
