# Generated by Django 5.1.6 on 2025-04-25 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_cart_donation_amount_cart_donation_enabled'),
        ('orders', '0005_alter_order_donate_to_goa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='donate_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='donate_to_goa',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_protection',
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='cart.cart'),
            preserve_default=False,
        ),
    ]
