# Generated by Django 5.1.6 on 2025-05-05 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_donate_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='donation',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AddField(
            model_name='order',
            name='protection_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
