# Generated by Django 5.1.6 on 2025-05-05 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_donation_order_protection_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='donation',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)]),
        ),
    ]
