version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: gunstore_db
      POSTGRES_USER: gunowner
      POSTGRES_PASSWORD: .env
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
