# Generated by Django 5.2.1 on 2025-05-22 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryLevel0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.CreateModel(
            name='CategoryLevel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level1_categories', to='categories.categorylevel0')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='CategoryLevel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level2_categories', to='categories.categorylevel1')),
            ],
            options={
                'verbose_name': 'Под-подкатегория',
                'verbose_name_plural': 'Под-подкатегории',
            },
        ),
        migrations.CreateModel(
            name='CategoryLevel3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level3_categories', to='categories.categorylevel2')),
            ],
            options={
                'verbose_name': 'Под-под-подкатегория',
                'verbose_name_plural': 'Под-под-подкатегории',
            },
        ),
        migrations.CreateModel(
            name='CategoryLevel4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level4_categories', to='categories.categorylevel3')),
            ],
            options={
                'verbose_name': 'Под-под-под-подкатегория',
                'verbose_name_plural': 'Под-под-под-подкатегории',
            },
        ),
    ]
