# Generated by Django 5.2.1 on 2025-05-22 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_categorylevel0_remove_category_parent_categorylevel1_and_more'),
        ('products', '0006_alter_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
