# Generated by Django 5.2.1 on 2025-05-27 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorylevel1',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='categorylevel2',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='categorylevel3',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='categorylevel4',
            name='parent',
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categories.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='CategoryLevel0',
        ),
        migrations.DeleteModel(
            name='CategoryLevel1',
        ),
        migrations.DeleteModel(
            name='CategoryLevel2',
        ),
        migrations.DeleteModel(
            name='CategoryLevel3',
        ),
    ]
