# Generated by Django 5.2.1 on 2025-05-27 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_remove_categorylevel1_parent_and_more'),
        ('products', '0007_alter_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryLevel4',
        ),
    ]
