# Generated by Django 5.1.6 on 2025-04-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shipping_protection',
            field=models.BooleanField(default=False),
        ),
    ]
