# Generated by Django 5.1.6 on 2025-04-25 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='shipping_protection',
        ),
    ]
