# Generated by Django 5.1.6 on 2025-04-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cart_shipping_protection'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shipping_protection',
            field=models.BooleanField(default=False),
        ),
    ]
