# Generated by Django 5.1.6 on 2025-04-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cart_shipping_protection'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='donation_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='donation_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
