# Generated by Django 5.1.6 on 2025-05-05 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='donation_amount',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='donation_enabled',
        ),
    ]
